name: scheffer-webdesign/form-manager-plus
label: Form Manager Plus
priority: 500
prototypes:
  standard:
    formEditor:
      dynamicJavaScriptModules:
        additionalViewModelModules:
          FormManagerPlusFocus: '@scheffer/form-manager-plus/focus.js'
          FormManagerPlusDescription: '@scheffer/form-manager-plus/editor-description.js'
